### ISSUE TITLE
cant install via pip

### ISSUE THREAD

**Issue by sugizo** [SKaplanOfficial/macimg#1]
**execute**
`pip install -U macimg`

**result**
```
Collecting macimg
  Downloading macimg-0.0.3-py3-none-any.whl (18 kB)
Collecting pyobjc-core~=9.0 (from macimg)
  Downloading pyobjc-core-9.2.tar.gz (923 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 923.8/923.8 kB 7.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

best regards

**Comment by SKaplanOfficial** [comment]
Hi, which version of Python are you using, and are you using an M-series chip or intel?

**Comment by sugizo** [comment]
**env**
`google colab`

**execute**
`!python -V`

**result**
`Python 3.10.12`

seems it's intel chip, 
because it run on ubuntu os

**execute**
`!uname -a`

**result**
`Linux 056c3f7b9e23 6.1.58+ #1 SMP PREEMPT_DYNAMIC Sat Nov 18 15:31:17 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

best regards

**Comment by SKaplanOfficial** [comment]
Ah, this package only works for macOS as it requires the Objective-C runtime. I'll update the description to better reflect this.
